;; This logfile was generated automatically by `xindy'
;; at 12.06.2025  21:36:24
;; Indexstyle: "/tmp/VTmxA2rexk", Rawindex: "/tmp/51QM_j2aCr", Output: "thesis.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "´¤†" -> "L"
Letter-group: "Ê†" -> "Q"
Letter-group: "Ê—" -> "Q"
Letter-group: "¼´Ã" -> "N"
Letter-group: "´Ê†" -> "L"
Letter-group: "ÊÈ" -> "Q"
Letter-group: "¤Ë" -> "H"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¤Ë" -> "H"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´¤†" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼´Ã" -> "N"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ê†" -> "Q"